language: objective-c
osx_image: xcode7.3
matrix:
    include:
        - xcode_workspace: Example-iOS/VOKBenkode.xcworkspace
          xcode_scheme: VOKBenkode-Example
          xcode_sdk: iphonesimulator
        - xcode_workspace: Example-iOS/VOKBenkode.xcworkspace
          xcode_scheme: VOKBenkode-tvOS
          xcode_sdk: appletvsimulator
        - xcode_workspace: Example-OSX/VOKBenkode.xcworkspace
          xcode_scheme: VOKBenkode-Example
          xcode_sdk: macosx
